### ISSUE TITLE
Access to SparkContext

### ISSUE THREAD

**Issue by mkamprath** [Tubular/sparkly#27]
The `SparklyContext` is a subclass of `HiveContext`, but [creates and throws out](https://github.com/Tubular/sparkly/blob/master/sparkly/context.py#L61) a `SparkContext` when it is constructing itself. I would like for that `SparkContext` to be retained, possibly as a property of the `SparklyContext`, so that I can access methods and operations only available through the `SparkContext`.

**Comment by drudim** [comment]
You already can access `SparkContext` using `HiveContext` (same true for `SparklyContext`): https://github.com/apache/spark/blob/branch-1.6/python/pyspark/sql/context.py#L100
```
hc = SparklyContext()
hc._sc  # SparkContext
```
We can proxy this object through a public property `sc` to make its usage "legal".

**Comment by mkamprath** [comment]
How "illegal" is using the `_sc` private variable? Do we expect it to be something that breaks? Looks like using it is fairly common, but I wouldn't want to create public API based on unsupported private API when the value itself is created in the class constructor.

**Comment by mkamprath** [comment]
@albertc1 To use that and ensure I get the same context that is driving the Sparkly session, I think I would need to ensure to use the same `SparkConf` settings object, which too is created in the Sparkly constructor and discarded.

**Comment by drudim** [comment]
@albertc1 nice idea!

Interesting thing, that in Spark 2.x they slightly changed the API, so `SparkSession` is the main entry point to DataFrame API and it has `sparkContext` property - http://spark.apache.org/docs/latest/api/python/pyspark.sql.html#pyspark.sql.SparkSession.sparkContext

We can try to mimic this behaviour in pyspark 1.6 by proxying `_sc` or `getOrCreate`.

**Comment by drudim** [comment]
Available in spark 2.x out-of-the-box.
