### ISSUE TITLE
Spark 2.x support.

### ISSUE THREAD

**Issue by zero323** [Tubular/sparkly#29]
Is there any ETA for Spark 2.0 support?

**Comment by drudim** [comment]
Should be ready by the end of January.

**Comment by zero323** [comment]
That's great. Thanks for the prompt response.

**Comment by drudim** [comment]
Here is a PR with expected changes: https://github.com/Tubular/sparkly/pull/35

**Comment by drudim** [comment]
sparkly 2.0.0 is now available on PyPi.
