### ISSUE TITLE
sparkly.writer depends on ujson which is not in requirements.txt

### ISSUE THREAD

**Issue by thesamet** [Tubular/sparkly#55]
This leads to an import error in a fresh installation.

**Comment by mantzouratos** [comment]
`ujson` is a redis-only requirement: https://github.com/Tubular/sparkly/blob/master/setup.py#L95 and is only imported if redis can be imported too: https://github.com/Tubular/sparkly/blob/master/sparkly/writer.py#L29-L39

Can you confirm this is what's happening with your environment?

**Comment by thesamet** [comment]
Yes, redis-py is installed in my environment, and I installed `sparkly`, but not `sparkly[redis]` (since I am not intended to use the redis writer).

**Comment by mantzouratos** [comment]
Fix here: https://github.com/Tubular/sparkly/pull/59 - will be included in sparkly 2.4.
