### ISSUE TITLE
Dependency conflicts due to pinned versions

### ISSUE THREAD

**Issue by Eric-Xu** [tubular/sparkly#69]
Can we change `six==1.10.0` to `six>=1.10.0` in requirements.txt to avoid dependency conflicts? We are using `sparkly` in several repos and hit a snag when another third party lib required `six>=1.11.0`.

**Comment by drudim** [comment]
@Eric-Xu thanks for letting us know about this issue. The fix is available in `v2.7.1`. Please, note, that `sparkly >= 2.7.0` is tested with `spark >= 2.4.0` only.

**Comment by Eric-Xu** [comment]
@drudim Thanks for your help on resolving this issue.
